### ISSUE TITLE
Unit test "test_arch_structure" fails

### ISSUE THREAD

**Issue by gilbertmike** [Accelergy-Project/timeloopfe#7]
Important error message seems to be:
```
Duplicate name elem_ref found in architecture. Duplicate name elem_ref found in architecture
```

I only found `elem_ref` in the following lines in `arch_nest.yaml`:
https://github.com/Accelergy-Project/timeloopfe/blob/95a79e2a0b59f54e7b920ad838852553dcfaf678/tests/arch_nest.yaml#L68-L80

**Comment by tanner-andrulis** [comment]
Thank you, fixed !
